### ISSUE TITLE
Support for tabs indentation

### ISSUE THREAD

**Issue by anfomin** [k--kato/vscode-docomment#10]
I'm using tag indentation option in VS Code:
```json
"editor.insertSpaces": false
```

But this extension always indent using spaces. It should read indentation information for current file from VS Code.

**Comment by k--kato** [comment]
@anfomin 
v.0.0.6
settings.json (`Code` > `Preferences` > `Workspace Settings`)
```json
{
    "editor.insertSpaces": false
}
```
```json
{
    "editor.insertSpaces": true,
    "editor.tabSize": 4
}
```

**Comment by anfomin** [comment]
@k--kato thank you!

**Comment by k--kato** [comment]
@anfomin my pleasure:)
