### ISSUE TITLE
Expansion is triggering in a lot of cases when it shouldn't

### ISSUE THREAD

**Issue by ivanz** [k--kato/vscode-docomment#16]
1. Those cases on the current line will trigger expansions currently, which is incorrect:

```
   /// ///
  /// text ///
```
1. Expansions shouldn't trigger if the previous or next lines are already doc comments:

```
     /// <--should not expand
    /// <summary>
```

```
    /// <summary>
  /// <--should not expand
```

**Comment by dmccaffery** [comment]
why was this reverted? its driving me nuts. :)

**Comment by k--kato** [comment]
@dmccaffery hmm.... https://github.com/k--kato/vscode-docomment/pull/18

**Comment by dmccaffery** [comment]
@k--kato ah; my bad. I hate the fact that referenced commits navigate directly to the source rather than the conversation when clicking the reference link.

**Comment by k--kato** [comment]
@dmccaffery I will fix this until this weekend.

**Comment by dmccaffery** [comment]
@k--kato Awesome! Much appreciated. 👍

**Comment by dmccaffery** [comment]
@k--kato you are fantabulous!
