### ISSUE TITLE
XML documentation file

### ISSUE THREAD

**Issue by youngdak** [k--kato/vscode-docomment#24]
Pls i can't find the xml documentation file in the bin directory of my project. How do i output it like in visual studio where you right click on the project -> properties -> build and check XML documentation file checkbox. Thanks.

![xmldoc](https://cloud.githubusercontent.com/assets/9219004/21560846/4cc3128a-ce65-11e6-8f29-95f87e431005.PNG)

**Comment by k--kato** [comment]
I'm afraid that this extension is not for Visual Studio, so I can't solve this issue, but please refer to this document.
https://msdn.microsoft.com/en-us/library/x4sa0ak0(v=vs.100).aspx
