### ISSUE TITLE
Output document puts cursor in wrong place

### ISSUE THREAD

**Issue by bbugh** [k--kato/vscode-docomment#26]
When using the snippet in my code, when I do the `///<tab>` shortcut, it outputs correctly, but the cursor is between slashes on the second line instead of in the blank spot. The error happens when auto documenting methods, member variables, and properties, but it works correctly on classes.

Here is a gif showing what I mean:

![lqs3z5vtgy](https://cloud.githubusercontent.com/assets/438465/21630457/e2749de6-d1f6-11e6-8db1-c5420c0303ad.gif)

- Mac OS Sierra
- VSCode v1.8.1
- vscode-docomment v0.0.10

**Comment by k--kato** [comment]
I can’t reproduce this bug. Please show me your `settings.json` or git repository.

```json
    "docomment.activateOnEnter": false,
    "editor.insertSpaces": true,
    "editor.tabSize": 4
```

**Comment by bbugh** [comment]
Sure thing. Here's my full settings.json:

```json
// Place your settings in this file to overwrite the default settings
{
    "workbench.activityBar.visible": false,
    "vscode_custom_css.imports": [
        "file:///Users/bbugh/projects/vscode_style.css"
    ],
    "editor.codeLens": false,
    "editor.fontSize": 14,
    "editor.fontFamily": "FiraCode, Menlo, Monaco, 'Courier New', monospace",
    "editor.lineHeight": 24,
    "files.autoSave": "onFocusChange",
    "bracketPairColorizer.colorMode": "Independent",
    "bracketPairColorizer.independentPairColors": [
        [
            "()",
            [
                "#c678dd",
                "Gold",
                "LightSkyBlue"
            ],
            "Red"
        ],
        [
            "[]",
            [
                "#c678dd",
                "Gold",
                "LightSkyBlue"
            ],
            "Red"
        ],
        [
            "{}",
            [
                "#c678dd",
                "Gold",
                "LightSkyBlue"
            ],
            "Red"
        ]
    ],
    "explorer.openEditors.visible": 0
     // "omnisharp.useMono": false
 }
```

It doesn't seem to be happening anymore, but the only setting I changed was the `omnisharp.useMono` back to the default of true. I wonder if that had something to do with it. 

Sorry to report an unreproducable bug. 😄 I don't wish those on anybody.

**Comment by bbugh** [comment]
I was wrong, it is still happening. Other than adding some code, I haven't made any changes to the project since I said it was working. I'm not sure why it's unreliable, but it's putting the cursor in the middle of my `///` again.

**Comment by ckohnert** [comment]
I am also encountering this (with 0.0.11), though my cursor winds up in a slightly different place.
 
![doccommentcursorplacementbug](https://cloud.githubusercontent.com/assets/826657/22036716/48480740-dca9-11e6-91a6-3019810b2fb3.gif)

My settings are the same as those listed above, but it looks like `editor.detectIndentation: true` (the default) is mucking things up. If I set it to false, it works as expected.
