### ISSUE TITLE
Adding /// in wrong place after pressing enter after text

### ISSUE THREAD

**Issue by bbugh** [k--kato/vscode-docomment#28]
When adding text to a `///` line and pressing enter, the next line doesn't have the `///` automatically. If I add it, it inserts a `///` into the last line. It's hard to describe in words so as always here's a picture worth a thousand:

![qryqfkyziz](https://cloud.githubusercontent.com/assets/438465/21814547/4263fd82-d71f-11e6-9925-b107bddb3392.gif)

If I do this on a blank line that only has `///` with whitespace after it, it doesn't happen. Hopefully this is easier to reproduce than my last bug!

**Comment by k--kato** [comment]
I'll release this, thank you 👍
duplicated #25
