### ISSUE TITLE
Wrapping lines in the middle of text inserts /// in the wrong place.

### ISSUE THREAD

**Issue by ckohnert** [k--kato/vscode-docomment#29]
If you hit Enter while in the middle of a sentence, it injects the '///' in the wrong place.

![wrapwithexistingtextbug](https://cloud.githubusercontent.com/assets/826657/22037845/c45ae0ce-dcad-11e6-8e62-ec013d772ab2.gif)

*Using version 0.0.11*

**Comment by k--kato** [comment]
This bug was reproduced by following settings.

* .vscode/setting.json
```json
{
    "docomment.activateOnEnter": false,
    "editor.insertSpaces": false,
    "editor.tabSize": 4,
    "editor.detectIndentation": true
}
```
