### ISSUE TITLE
Please make the new line in comment also start with "///"

### ISSUE THREAD

**Issue by haolly** [k--kato/vscode-docomment#40]
When I  Start  write a new Line comment, press enter in `<summary>` and `</summary> ` will create an empty line, then I need type three **/** character to start write comment, but, the problem is when I type three **/** character, the next line will be indented by another **///** , which is annoying

**Comment by bgever** [comment]
Related to this, when hitting enter after the `</summary>` tag, it should start with an empty line prefixed with `/// `, and not add another `<summary>` element. I often need to do this to add a `<remarks>` element.

**Comment by PJB3005** [comment]
I actually fixed this in #47 in theory but I guess it was broken, or it was some obscure cross platform issue. Working on it.

**Comment by PJB3005** [comment]
Oh my god I figured it out. It doesn't work on windows because `IsEnterKey` breaks on CRLF EOLs (windows) as the first char in the string is a carriage return, not a newline.

**Comment by bgever** [comment]
Thanks for the fix!

**Comment by k--kato** [comment]
@bgever Thanks for your PR.
