### ISSUE TITLE
Activate on Enter

### ISSUE THREAD

**Issue by TheColorRed** [k--kato/vscode-docomment#9]
Most of the comment documentors activate the comment block once the user presses <kbd>Enter</kbd> instead of when they type `///`.

For me, I like making comment blocks that look like this:

```
///////////////////////////////////////////////////////////////////////////
/// Comment block that sticks out!
///////////////////////////////////////////////////////////////////////////
```

When I do so it attempts to make a document block.

So if you could make it so when you pressed <kbd>/</kbd><kbd>/</kbd><kbd>/</kbd><kbd>Enter</kbd> it gets activated instead of the current way, that would be awesome!

**Comment by k--kato** [comment]
v.0.0.6
settings.json (`Code` > `Preferences` > `Workspace Settings`)
```json
{
    "docomment.activateOnEnter": true
}
```
